#!/bin/sh
# autopkgtest check: very few things to test without other subcommands
# (C) 2021 Jose Luis Rivero
# Author: Jose Luis Rivero <jrivero@osrfoundation.org>

set -e

WORKDIR=$(mktemp -d)
#trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR

cat <<EOF > CMakeLists.txt
cmake_minimum_required(VERSION 3.5.1 FATAL_ERROR)

project(example)

# Find the ignition-plugin2 library
find_package(ignition-plugin2 REQUIRED COMPONENTS all)
#include_directories(\${ignition-plugin2_INCLUDE_DIRS})
add_executable(plugin_test plugin_test.cc)
target_link_libraries(plugin_test
  PRIVATE
    ignition-plugin2::register
    ignition-plugin2::loader
)

EOF

cat <<EOF2 > plugin_test.cc
#include <ignition/plugin/Loader.hh>
#include <ignition/plugin/Register.hh>

class Drive
{
  public: virtual ~Drive() = default;
};


class CautiousBot : public virtual Drive
{
};

IGNITION_ADD_PLUGIN(CautiousBot,
    CautiousBot::Drive)

int main(int argc, char** argv) {
  ignition::plugin::Loader pl;

  return 0;
}
EOF2

cmake .
echo "configure: OK"
make
echo "build: OK"

./plugin_test
echo "plugin_test run: OK"

